Bookers/config/routes.rb
Rails.application.routes.draw do
 # get 'reviews/show'
 # get 'reviews/index'
 # get 'reviews/edit'
 get "/" => "reviews#top"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 resources :reviews
end

Bookers/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Bookers/app/models/review.rb
class Review < ApplicationRecord
end

Bookers/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

Bookers/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def top

  end


  
  def show
	@review = Review.find(params[:id])
  end

  def index
	@reviews_all = Review.all
	@review_new = Review.new
	#@rerere = Review.find(id: 1)
  end

  def create
	review=Review.new(review_params)
	review.save
	flash[:notice]="Book was successfully created."
	redirect_to review_path(review)
	
  end


  def edit
	@review = Review.find(params[:id])
  end

  def update
	review = Review.find(params[:id])
	review.update(review_params)
	flash[:notice]="Book was successfully updated"
	redirect_to review_path(review)

  end

  def destroy
	review = Review.find(params[:id])
	review.destroy
	redirect_to reviews_path
  end

  private
  def review_params
    params.require(:review).permit(:title, :body)
  end

end

Bookers/app/helpers/application_helper.rb
module ApplicationHelper
end

Bookers/app/helpers/reviews_helper.rb
module ReviewsHelper
end

Bookers/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
	  <% if flash[:notice] %>
		  <div class="flash"%>
			<%= flash[:notice]%>
		  </div>
	  <% end %>
	  <%= yield %>
  </body>
</html>

Bookers/app/views/reviews/edit.html.erb
<h1>Editing Book</h1>

<%= form_for(@review) do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title, class:"book_title" %>
  <h4>Body</h4>
  <%= f.text_area :body, class:"book_body" %></br>
    
  <%= f.submit 'Update Book' %>
<% end %>

<%= link_to("Show", review_path(@review), class:"show_#{@review.id}") %> |
<%= link_to("Back", reviews_path, class:"back") %>

Bookers/app/views/reviews/index.html.erb
<h2>Books</h2>
<table>
  <tr>
    <th>Title</th>
    <th>Body</th>
  </tr>
  <% @reviews_all.each do |review| %>
  <tr>
    <td><%= review.title %></td>
    <td><%= review.body %></td>
    <td><%= link_to("show", review_path(review), class:"show_#{review.id}") %></td>
    <td><%= link_to("edit", edit_review_path(review), class:"edit_#{review.id}") %></td>
    <td><%= link_to("destroy", review_path(review), method: :delete, "data-confirm" => "Are you sure?", class:"destroy_#{review.id}") %></td>
  </tr>
  <% end %>
</table>

  

  
<h2>New Book</h2>
<!-- form_for部分 -->
<%= form_for(@review_new) do |f| %>

<h4>Title</h4>
<%= f.text_field :title, class:"book_title" %>

<h4>Body</h4>
<%= f.text_area :body, class:"book_body" %></br>

<%= f.submit 'Create Book' %>

<% end %>

Bookers/app/views/reviews/show.html.erb
<body>
  <p id="notice"></p>

  <p>
    <strong>Title:</strong>
    <%= @review.title %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= @review.body %>
  </p>

  <%= link_to("Edit", edit_review_path(@review),class:"show_#{@review.id}") %> |
    <%= link_to("Back", reviews_path, class:"back") %>

Bookers/app/views/reviews/top.html.erb
<h1>
  ようこそ <strong>Bookers</strong>  へ！
</h1>
<p>
  <strong>Bookers</strong>  では、さまざまな書籍に関するあなたの意見や
</p>
<p>印象を共有し交換することができます</p>
<p>
  <%= link_to("start", "/reviews")%>
</p>